# name of the software
name: Python in BrainVoyager
# current version of the software
version: 20.2
# url of the download button
downloadUrl: #
# licence of the software
#license: Creative Commons BY 3
#licenseUrl: http://creativecommons.org/licenses/by/3.0/

# list of additional links on the right of the top menu
headerLinks:
    #- title: GitHub
    #url: https://github.com/mistic100/jekyll-bootstrap-doc

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/fladd/BVPython/tree/gh-pages
  - title: Issues
    url: https://github.com/fladd/BVPython/issues?state=open

# header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: true

# Author information
author:
    name: Florian Krause
    website: http://fladd.de

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: #fladd
  repo: #BVPython

# twitter buttons
twitter:
  enabled: false
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: false
  profileUrl:


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
